### ISSUE TITLE
Include progress report in output

### ISSUE THREAD

**Issue by boegel** [eth-cscs/reframe#1092]
When `reframe` is running a large number of tests, it's hard to tell how far it has progressed.

It would be nice if a simple `X/N tests done` could be included in the output while `reframe` is running.

Maybe also mention how many tests have succeeded/failed so far, how many are held because of dependencies or awaiting resources, etc.

**Comment by vkarak** [comment]
@boegel I think that this feature should be implemented inside the [PrettyPrinter](https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/printer.py#L7). This takes care of the actual printing including colours, text justification etc. Currently, it is practically stateless; the execution policies and the [Runner](https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/executors/__init__.py#L254) call the [status](https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/printer.py#L32) method to print status messages. Status messages are not only the final `OK/FAIL/ERROR` but also intermediate ones, such as the `RUN` lines. We need to extend the printer with a method to initialize the progress, e.g., `init_progress()`, that would take the number of test cases and initialize the counter to zero. We should have a separate method for that, because we need to reset the counter when we retry the tests when the `--max-retries` option is passed. This happens [here](https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/printer.py#L32).

Instead of patching the `status()` and increment the progress counter based on the status message, I suggest adding a couple of check-specific printer methods for the three statuses: `test_ok(check)`, `test_fail(check)`, `test_error(check)`. These will increment the progress counter and delegate the status printout to the current `status()` method:

```python
def test_ok(self, check):
    self._progress_count += 1
    self.status('OK', check.info(), just='right')
```

This would also require an additional replacement of the raw status call inside the policies.

Regarding the output what about the following?

#### Serial policy

```
[----------] started processing Example7Test (Matrix-vector multiplication (CUDA performance test))
[ RUN      ] Example7Test on daint:gpu using PrgEnv-cray
[       OK ] (1/3) Example7Test on daint:gpu using PrgEnv-cray
[ RUN      ] Example7Test on daint:gpu using PrgEnv-gnu
[       OK ] (2/3) Example7Test on daint:gpu using PrgEnv-gnu
[ RUN      ] Example7Test on daint:gpu using PrgEnv-pgi
[       OK ] (3/3) Example7Test on daint:gpu using PrgEnv-pgi
[----------] finished processing Example7Test (Matrix-vector multiplication (CUDA performance test))
```

#### Asynchronous policy

```
[----------] waiting for spawned checks to finish
[       OK ] (1/10) MPITest on daint:gpu using PrgEnv-pgi
[       OK ] (2/10) MPITest on daint:gpu using PrgEnv-gnu
[       OK ] (3/10) OpenMPTest on daint:mc using PrgEnv-pgi
[       OK ] (4/10) OpenMPTest on daint:mc using PrgEnv-gnu
[       OK ] (5/10) OpenMPTest on daint:gpu using PrgEnv-pgi
[       OK ] (6/10) OpenMPTest on daint:gpu using PrgEnv-gnu
<output omitted>
```

I don't know what else you would like to see in the output as progress, but the above implementation proposal should be enough for the above output.

**Comment by vkarak** [comment]
@boegel Did you have time to look into that?

**Comment by boegel** [comment]
@vkarak Not yet, I'm sorry. I'm still hoping to find time for it, but I can't make any promises...

**Comment by vkarak** [comment]
Sure, not a problem. I just wanted to check the status, in case sb from us wants to work on that.
