### ISSUE TITLE
Change default compilers

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#1153]
In the configuration, the default compilers are set to the Cray ones. https://github.com/eth-cscs/reframe/blob/3f5e97fdbdd2a2386b0bbd8570cb3a2e795c43bd/schemas/config.json#L345-L347

My proposal is to change them to a more generic "Linux-like" set of compilers, such as 
```
"environments/cc": "cc",
"environments/cxx": "c++",
"environments/ftn": "gfortran",
```

The drawback is that there is no such thing as "default fortran", but I think one can survive with `gfortran` as the default.

**Comment by vkarak** [comment]
Closing this, since it's a breaking only change. It won't bring any value to Linux boxes, but it will break any existing Cray installation that relies on these defaults. And POSIXly speaking only the C compiler is standard, so even `c++` is just a convention that happens to work on both Linux and Mac.
