### ISSUE TITLE
Parametrizing tests based on module discovery

### ISSUE THREAD

**Issue by mboisson** [eth-cscs/reframe#1159]
It would be a really great feature if ReFrame could parametrize tests based on the available modules. For example, something like this : 

```
@rfm.parameterized_test(*utility.all_modules('gromacs',min_version,max_version))
```

**Comment by vkarak** [comment]
An optional callable argument that would allow custom version comparisons would be useful, I guess, too. We don't want to implement all version conventions.

**Comment by davidedelvento** [comment]
Yes, this would be fantastic!!!

For sites running lmod, this could be easily and relatively robustly implemented using [spider json format](https://lmod.readthedocs.io/en/latest/136_spider.html)

For everyone else, I guess the output of `module available` will need to be parsed. I've already implemented such a parser for our system., it's just 60 lines of (dense) python code. If it can be of any help, I'll be happy to clean it up, improve the unit tests I have written (which are not well done) and contribute it to this project.

**Comment by vkarak** [comment]
> For sites running lmod, this could be easily and relatively robustly implemented using spider json format

Exactly!

> If it can be of any help, I'll be happy to un-densify it, make it clearer for other to read, improve the unit tests I have written (which are not well done) and contribute it to this project.

Contributions are always welcome ;-)

**Comment by vkarak** [comment]
This one turns out to be less straightforward than it seems. We should answer what are the modules over which we want to parametrize? The decorator will run at test loading, before even the test is filtered per partition and programming environment. If you have the same package built for arch A and B, which is exposed by loading different base modules, then for which of the two would you parametrize the test? You would end up having different tests for each programming environment (compiler/toolchain) as well as target system. @victorusu who's working on that may have more details.

**Comment by victorusu** [comment]
I started to implement this feature, but because decorators are executed before the class instantiation. I have two questions/difficulties:

1. Qhat happens if one needs to load a module before having access to the module in question? e.g. at CSCS in order to load GROMACS one needs to 
```
module load daint-gpu # or module load daint-mc
module load GROMACS
```
ReFrame is aware of those `daint-gpu` and `daint-mc` modules but at the virtual partition level.


2. What happens if the test needs to preload the programming environment before accessing the module in question? e.g. if one uses hierarchical module schemes, then one might need to first load the compiler, then load the MPI implementation, etc before the module becomes available.



Can you guys give me suggestions?

**Comment by mboisson** [comment]
Can't we rely on module spider ? It tells you what you need to load before getting the module

**Comment by victorusu** [comment]
@mboisson, for point number two yes. But what about number one (assuming that you do not have a Lmod installation)?

**Comment by mboisson** [comment]
Maybe there can be a syntax to say which primary modules to try loading first ?

**Comment by vkarak** [comment]
All these are good and can be done, but the don't address the following scenario. Assume the following test:
. 
```python
@parameterized_test(*available_modules('gromacs'))
class GromacsTest(...):
    def __init__(self, modules):
        self.valid_systems = ['x:gpu', 'x:skylake', 'x:knl']
        self.valid_prog_environs = ['gnu', 'intel']
        self.modules = modules
```

And that we have different s/w  stacks for each compiler and for each arch. If we use spider that would give all the module combinations, for example, `gnu/gromacs/20.1`, `gnu/gromacs/20.2`, `intel/gromacs/20.1`, `cuda/gromacs/20.1`, `cuda/gromacs/20.2`, then you will end up with a test for `x:gpu` that would load the `intel/gromacs` module. You will have therefore to set the `valid_systems` and `valid_prog_environs` based on the `modules` parameter, which has a  bit the inverse logic, where normally you set the modules in the test based on the system and programming environments and not vice versa. But if you're fine with that, I don't have a problem. 

Another complication comes for modules systems other than Lmod. In that case, as @mboisson said, you can extend the interface of `available_modules` to pass the primary modules first, but this parameter should be multi-dimensional to cover the different combinations. Because if I call simply `available_modules('gromacs', ['intel', 'openmpi'])`, I would only generate the `intel/opempi/gromacs` versions.

The interface needs a bit of thinking still, I believe.

**Comment by davidedelvento** [comment]
I personally do not thing that the "inverse logic" is a big problem. 

Moreover, one option would be to make up a syntax by which the test author can specify the modules that need to be tested. For your example, one could use a regular expression (just because the syntax already exist, everybody knows them and their parsers are already robustly implemented) to match `gnu/gromacs/20.1`, `gnu/gromacs/20.2` and `intel/gromacs/20.1`, but not `cuda/gromacs/20.1` and `cuda/gromacs/20.2` for one test and vice versa for the other (if that is what is desired).

**Comment by vkarak** [comment]
Since as it seems, this needs still a bit more thinking, I will postpone it to 3.2 for the moment.

**Comment by vkarak** [comment]
Eventually, we came up with @victorusu with sth that works nicely with both flat and hierarchical modules schemes and respects ReFrame's concept of environments and systems. Here is a proof-of-concept:

```python
import functools
import re
import reframe as rfm
import reframe.core.runtime as rt


def find_modules(module, toolchain_mapping=None):
    def _is_valid_for_env(m, e):
        if toolchain_mapping is None:
            return True

        for patt, toolchains in toolchain_mapping.items():
            if re.match(patt, m) and e in toolchains:
                return True

        return False

    ms = rt.runtime().modules_system
    current_system = rt.runtime().system
    snap0 = rt.snapshot()
    for p in current_system.partitions:
        for e in p.environs:
            rt.loadenv(p.local_env, e)
            modules = ms.available_modules(module)
            snap0.restore()
            for m in modules:
                if _is_valid_for_env(m, e.name):
                    yield (p.fullname, e.name, m)


cscs_find_modules = functools.partial(find_modules, toolchain_mapping={
    r'.*CrayGNU.*': {'PrgEnv-gnu'},
    r'.*CrayIntel.*': {'PrgEnv-intel'},
    r'.*CrayCCE.*': {'PrgEnv-cray'},
})


@rfm.parameterized_test(*find_modules('netcdf'))
class MyTest(rfm.RegressionTest):
    def __init__(self, s, e, m):
        self.descr = f'{s}, {e}, {m}'
        self.valid_systems = [s]
        self.valid_prog_environs = [e]
        self.modules = [m]
```

The `toolchain_mapping` parameter (names can be improved) must be used with flat schemes and essentially defines a mapping from the module name (and, particularly, the toolchain part) to ReFrame's environments as they are defined in its configuration file. Sites with flat schemes, like CSCS, are expected to pass this parameter, otherwise `find_module()` will return incompatible module and environment combinations. The function assumes the extension to the internal modules API that #1417 is implementing. Here is what `cscs_find_modules('GROMACS')` would produce with our software stack:

```
[List of matched checks]
  - MyTest_dom_gpu_PrgEnv_gnu_GROMACS_2018_6_CrayGNU_20_08_cuda (found in /users/karakasv/Devel/misc/reframe-tests/find_modules_test.py)
  - MyTest_dom_gpu_PrgEnv_gnu_GROMACS_2020_3_CrayGNU_20_08_cuda (found in /users/karakasv/Devel/misc/reframe-tests/find_modules_test.py)
  - MyTest_dom_mc_PrgEnv_gnu_GROMACS_2020_1_CrayGNU_20_08 (found in /users/karakasv/Devel/misc/reframe-tests/find_modules_test.py)
  - MyTest_dom_mc_PrgEnv_gnu_GROMACS_2020_3_CrayGNU_20_08 (found in /users/karakasv/Devel/misc/reframe-tests/find_modules_test.py)
```

The plan is to incorporate `find_modules()` as a utility in an upcoming PR.
