### ISSUE TITLE
logging inside regression test

### ISSUE THREAD

**Issue by njhdunn** [eth-cscs/reframe#1261]
I'm running into some trouble with using the logging interface in my tests. Specifically, using `self.logging.log()` or any of the wrapper functions for it within a regression test fails when I have more than one logging target defined in the reframe configuration.

I define a logging configuration:

```
    logging_config = {
        'level': 'DEBUG',
        'handlers': [
            {
                'type': 'file',
                'name': 'reframe.log',
                'level': 'DEBUG',
                'format': '[%(asctime)s] %(levelname)s: '
                          '%(check_info)s: %(message)s',
                'append': False,
            },

            # Output handling
            {
                'type': 'stream',
                'name': 'stdout',
                'level': 'DEBUG',
                'format': '%(message)s',
            },
            {
                'type': 'file',
                'name': 'reframe.out',
                'level': 'DEBUG',
                'format': '%(message)s',
                'append': False,
            }
        ]
    }
```
And I call the logger from within the regression test via:

```
	@rfm.run_after('run')
	def _meta_add_logs(self):
		log_level_names = rfm.core.logging._log_level_names

		# These only print correctly to first log in configuration file
		for level in log_level_names:
			self.logger.log(level, "logging {0}".format(level))
```

I would like to be able to dynamically add selected test results to the logging targets for a reframe run, but when I have more than one target (like reframe.log, reframe.out, stdout) only the first of the logging targets is generated correctly. The other logging targets generate an error message:

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/msistaff/dunn0404/.conda/envs/reframe_deps/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/home/msistaff/dunn0404/.conda/envs/reframe_deps/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/panfs/roc/groups/14/msistaff/dunn0404/install_tests/ReFrame/reframe-3.0-dev3/reframe/core/logging.py", line 161, in format
    ct = self.converter(record.check_job_completion_time)
TypeError: an integer is required (got type str)
```

The issue seems to be related to the format of the date. On the first pass through the format function, the date is in the expected epoch format and can be converted. In subsequent passes, the date has already been formatted into the human-readable format specified in the config file, and the format function fails with the above message.

I am including a minimum failing example that can be run to generate the described behavior.

[logging_issue.tar.gz](https://github.com/eth-cscs/reframe/files/4462499/logging_issue.tar.gz)

**Comment by vkarak** [comment]
Hi @njhdunn, I was able to reproduce this, but I'm trying to see how it is triggered.

**Comment by vkarak** [comment]
It's certainly a bug from the framework. Thanks @njhdunn for reporting. You can actually reproduce with any test by just increasing the verbosity level:

```
./bin/reframe -c unittests/resources/checks/hellocheck.py -r -vv
```

The problem seems to come from [here](https://github.com/eth-cscs/reframe/blob/master/reframe/core/logging.py#L180), where we're overwriting the record's `check_job_completion_time`. It seems that the formatting function is called twice and the second time it will have a value (`str`) that cannot be passed to the converted in the line above.

I will update the title of this issue and convert it to a bug.

**Comment by victorusu** [comment]
If I monkey patch the [`format` method of `RFC3339Formatter`](https://github.com/eth-cscs/reframe/blob/c5a01bb8a1d7984e14af04f697c88d57b55cf8e0/reframe/core/logging.py#L176) to
```
class RFC3339Formatter(logging.Formatter):
...
    def format(self, record):
        datefmt = self.datefmt or self.default_time_format
        if record.check_job_completion_time is not None:
            if isinstance(record.check_job_completion_time, int):
                ct = self.converter(record.check_job_completion_time)
                record.check_job_completion_time = _format_time_rfc3339(
                    ct, datefmt
                )   
            else:
                ct = record.check_job_completion_time

        return super().format(record)
```
The problem is gone.

I do not think this is the correct solution, but it could work as workaround while we properly fix the problem.

**Comment by vkarak** [comment]
@victorusu The fix seems reasonable. The problem comes from the fact that the `record.check_job_completion_time` is used for two purposes: first to hold the raw job completion timestamp and second the formatted timestamp. Perhaps a better solution would be to hold the raw completion time in a separate variable (through a "hidden" extra [here](https://github.com/eth-cscs/reframe/blob/c5a01bb8a1d7984e14af04f697c88d57b55cf8e0/reframe/core/logging.py#L438)).
