### ISSUE TITLE
perflog is missing when perf_patterns is defined inside a decorator function

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#1376]
If you look at the code in [UES-911](https://github.com/jgphpc/reframe/tree/UES-911),

> reframe -C ./jg.py --system dom:login -r -p PrgEnv-gnu -c ko.py

will not generate `perflogs/dom/login/ExampleRunLoggingTest.log` while ok.py does.

Is this an issue with jg.py ?

**Comment by ekouts** [comment]
I think the problem is that the setup for the performance logging happens here, in the [setup phase](https://github.com/eth-cscs/reframe/blob/master/reframe/core/pipeline.py#L1090). One solution could be to call `self._setup_perf_logging()` anyway, but @vkarak do we want this? Or should we add something in the documentation about it? As a workaround @jgphpc, maybe you can set the `self.perf_patterns` with the decorator `@rfm.run_before('setup')`.

**Comment by vkarak** [comment]
@ekouts this is the reason why this is happening. Technically it is not really a bug, but what @jgphpc requests here makes sense, since it's much more natural to be able to define `perf_patterns` just before the `performance` phase, as we can do for the `sanity_patterns`.
