### ISSUE TITLE
ReFrame demands `jsonschema` even if a JSON site config is not used

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#1446]
Greetings,

NERSC has finally completed the herculean upgrade to ReFrame 3. However we have encountered a problem, which is that ReFrame 3 depends on `jsonschema`, which is not installed at the moment. NERSC does not use JSON for its site-config anyway, so I wonder if it is possible to make this requirement optional? Could ReFrame import `jsonschema` only if it detects a config file which is indeed JSON?

Other than this, ReFrame 3 is running smoothly, and we're very happy with it!

**Comment by vkarak** [comment]
Hi @bcfriesen, nice to hear that you have finished the migration and everything runs smoothly now! Have you tried the `bootstrap.sh` script from ReFrame 3.1? This will install the dependencies of ReFrame in a folder where ReFrame always looks at, so that you don’t need to create any virtual environments or custom Python installations. It should work out of the box. Just run `./bootstrap.sh` in the installation directory of ReFrame and it should be ready to go. All is needed is a working Python 3.6+. We’ve even tested this with the vanilla Cray Python on XC50 and it works.

**Comment by bcfriesen** [comment]
Hi @vkarak - thanks for the info, this is helpful. You're always 2 steps ahead of us!

The v2.21 -> v3.0 migration was ... a lot of work. Hopefully the 3.0 -> 3.1 transition will be better. The `bootstrap.sh` approach sounds great, I'll test that out when I summon the energy to do this again :-D

**Comment by vkarak** [comment]
The 3.0 to 3.1 transition should be pretty much straightforward, since nothing fundamental has changed in the framework or the API.

**Comment by vkarak** [comment]
I'm closing this since it's fixed in 3.1.
