### ISSUE TITLE
Implement max_pending_time for the PBS scheduler

### ISSUE THREAD

**Issue by ekouts** [eth-cscs/reframe#1473]

**Comment by vkarak** [comment]
This is not trivial to implement as of now for the PBS scheduler, because we don't use the `qstat` command there, so we don't know while polling if a job is actually running of pending. It would be meaningful only if use `qstat` for the PBS backend as well, in which case, the Torque/PBS schedulers must be refactored: either the `poll()` of Torque be moved in PBS or the make the PBS scheduler inherit from Torque.
