### ISSUE TITLE
Wrong node allocation description

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#1520]
When using the `-L/--list-detailed` in order to get detailed information about one of my self-backed tests, ReFrame reports the following:
```bash
...
    Node allocation:
      standard (1 task(s))
... 
```
This is misleading information because I have the following seam in my code
```
...
    @rfm.run_after('setup')
    def set_num_tasks(self):
        if self.current_partition.fullname in ['daint:gpu', 'dom:gpu']:
            self.num_tasks = 72
            self.num_tasks_per_node = 12
            self.num_cpus_per_task = 1
...
```

I do not know what to do here, because I understand that the information is taken from after `init`.
And if ReFrame executes all steps up to `compile` (excluding `compile`) to display the information, I could still write:
```
...
    @rfm.run_after('compile')
    def set_num_tasks(self):
        if self.current_partition.fullname in ['daint:gpu', 'dom:gpu']:
            self.num_tasks = 72
            self.num_tasks_per_node = 12
            self.num_cpus_per_task = 1
...
```

One cannot execute compile to give me the `-L` flag because in this particular case, for instance, it takes 20 min to compile the test... 😄 

My proposal is to either remove this entry from `-L` or change the wording, in case, there is a hook for any other phase after `init`. An example would be
```
...
    Node allocation (assumed):
      standard (1 task(s))
... 
```

The word *assumed* has to be replaced by a better word, but you get the idea.

**Comment by vkarak** [comment]
As you mention, the information printed in the detailed listing is before running the test, i.e., before entering the `setup()`. Technically, this is not a bug, but perhaps not well documented. ReFrame tests can be very dynamic, so there is no way to get accurate information after they are initialized. Suggesting to remove this raises the question, why then not remove all other detailed information, since this can also be defined entirely outside the `__init__()`! If we keep the minimum that can be defined, then we will end up reporting only the valid systems and valid programming environments.

**Comment by vkarak** [comment]
Ok, this is valid. What about printing something like that if there are hooks?

```
    Node allocation:
      standard (1 task(s) -- may be set differently in hooks)
```
