### ISSUE TITLE
More detailed information about dependencies

### ISSUE THREAD

**Issue by victorusu** [eth-cscs/reframe#1521]
In one of my tests, reframe reports the `-L` reports
```
- BTest:
    Dependencies:
      ATest
...
    Valid environments:
      builtin, PrgEnv-gnu

    Valid systems:
      daint:gpu, dom:gpu, daint:mc, dom:mc
```

But my `BTest` only depends on `ATest` when
* The `ATest` has partition `login` and programming environment `PrgEnv-gnu`; and
* The `BTest` has partition `gpu` and programming environment `builtin` or `PrgEnv-gnu`

I have the following seam in my `BTest` class
```
        self.valid_systems = ['daint:gpu','dom:gpu', 'daint:mc','dom:mc']
        self.valid_prog_environs = ['builtin', 'PrgEnv-gnu', 'PrgEnv-intel']
...
        subdeps = {('gpu', 'builtin'): [('login', environment)]}
        subdeps[('gpu', 'PrgEnv-gnu')] = [('login', environment)]
        self.depends_on('ATest', how=rfm.DEPEND_EXACT, subdeps=subdeps)
...
```
> Note: My test is based on PR #1481.

 I wanted to know in which conditions `BTest` depends on the `ATest` test. I would love to see something like the following (or better)
```
- BTest:
    Dependencies:
      ATest('login', 'PrgEnv-gnu') when ('gpu', 'builtin')
      ATest('login', 'PrgEnv-gnu') when ('gpu', 'PrgEnv-gnu')
...
    Valid environments:
      builtin, PrgEnv-gnu, PrgEnv-intel

    Valid systems:
      daint:gpu, dom:gpu, daint:mc, dom:mc
```

**Comment by vkarak** [comment]
That's a valid request. Perhaps it's not gonna be reported as you propose exactly, but we should provide more detailed information about the exact dependencies.

**Comment by ekouts** [comment]
>I wanted to know in which conditions BTest depends on the ATest test. I would love to see something like the following (or better)
```
- BTest:
    Dependencies:
      ATest('login', 'PrgEnv-gnu') when ('gpu', 'builtin')
      ATest('login', 'PrgEnv-gnu') when ('gpu', 'PrgEnv-gnu')
...
    Valid environments:
      builtin, PrgEnv-gnu, PrgEnv-intel

    Valid systems:
      daint:gpu, dom:gpu, daint:mc, dom:mc
```

@vkarak This is doable, but the code as it is now it prints information about the checks (`RegressionTest` objects). For example valid systems can be just `*`, instead of a list of the ones that apply on this system. Should we make the listing more detailed in general and get the information from the testcases (`TestCase` objects)?

**Comment by vkarak** [comment]
Couldn't you print the whole list of micro-dependencies? We have the test cases at this point. Something like that:

```python
- B:
    Dependencies:
      ('B', 'gpu', 'builtin') -> ('A', 'login', 'gnu')
      ('B', 'gpu', 'gnu') -> ('A', 'login', 'gnu')
```

I'm fine to have a different notation for the test DAG vertices, e.g., `B['gpu', 'builtin']` but is should be consistent everywhere. Also, I think we should always prepend the current system in the partition, because this will make it easier for the user understand, e.g., `('B', 'daint:gpu', 'builtin')`.

**Comment by ekouts** [comment]
> Couldn't you print the whole list of micro-dependencies? We have the test cases at this point.

Yes, we have the testcases at that point. I was asking if you think it is better to get all the information from test cases, and not print for example:
```
Valid systems:
      *
```
but print the actual partitions that it will run on:
```
Valid systems:
      daint:gpu, dom:gpu
```

> I'm fine to have a different notation for the test DAG vertices, e.g., B['gpu', 'builtin'] but is should be consistent everywhere. Also, I think we should always prepend the current system in the partition, because this will make it easier for the user understand, e.g., ('B', 'daint:gpu', 'builtin').

I will go with `('B', 'gpu', 'builtin') -> ('A', 'login', 'gnu')` since this is what we are using everywhere else.
