### ISSUE TITLE
Utility function 'osext.cray_cdt_version' returns 'None' on eiger

### ISSUE THREAD

**Issue by ajocksch** [eth-cscs/reframe#1744]
The call of osext.cray_cdt_version() does not return the cdt version on eiger but something like novalue

**Comment by teojgo** [comment]
I don't know if a cdt makes sense for this system. Maybe we could provide a more suitable utility function.

**Comment by vkarak** [comment]
I agree, CDTs are not part of Eiger. I don't what else could make sense there.

**Comment by teojgo** [comment]
@lucamar any idea what could be an equivalent to a cray CDT version in this case?

**Comment by lucamar** [comment]
@teojgo Unfortunately nothing is appropriate at present, since even default modules do not correspond to the default PE (e.g.: `CRAY_LIBSCI_VERSION` and `PERFTOOLS_VERSION` feature 20.12 in the release, while the default PE is `20.10`). We hope to get something equivalent in PE 21.03, see https://jira.cscs.ch/browse/SD-50894.

**Comment by vkarak** [comment]
@ajocksch This is not a problem of the `osext.cray_cdt_version()` function. The documentation states it is expected to return `None` for non-Cray systems, which admittedly is a bit misleading. I will update the documentation:

> Return the Cray Development Toolkit (CDT) version or None for non-Cray systems
