### ISSUE TITLE
feature request: configurable nodelist pattern

### ISSUE THREAD

**Issue by ebirn** [eth-cscs/reframe#2357]
Greetings!

We've started using reframe more extensively recently, it's a great tool!

In the (error) reports I've noticed our node-names are cut off in the abbreviated node list, due to their naming.
Examples are: 
clip-c1-3
clip-c1-14
clip-c2-54
clip-m1-2
clip-g3-3
stg-c1-3
dev-c2-5
etc..

I've seen the matching pattern: r'(^\D+)(\d+)'
https://github.com/eth-cscs/reframe/blob/master/reframe/utility/__init__.py#L768
as a result, multiple clip-c2-* nodes might show up as just "clip-c2"

checking on https://pythex.org shows that for our site, this pattern would work: (^\w+-\w\d+-)(\d+)$
I've patched this locally and it "works for me".

As this might be relevant to other sites too, is it feasible to have this pattern configurable in the settings?
I assume it would be ideal to have it in the per-system settings.

Best,
Erich

**Comment by vkarak** [comment]
Hi @ebirn, thanks for the appreciation and thanks for reporting this. The intent of this regular expression was to match anything that ends with digits and get the last set of digits as the node id. I wouldn't make this a configurable parameter yet, since I believe it's a detail. We will try to fix the regex to represent correctly its original intent.
