### ISSUE TITLE
Support saving energy consumption and GPU usage data

### ISSUE THREAD

**Issue by omlins** [eth-cscs/reframe#239]
It would be nice to store energy consumption and GPU usage data with ReFrame in order to be able to analyse it later. The correlation between measured energy consumption (per time) and performance could reveal many interesting things. As much as I know, main memory access (GPU memory / CPU memory) is what consumes most energy and the total amount of transferred data should not change normally between different runs of the same application, the source code not being changed...

**Comment by jgphpc** [comment]
Is this a joke ?

**Comment by vkarak** [comment]
I suppose this enhancement is for the user tests side, am I right?

**Comment by teojgo** [comment]
It could go to the settings file as it applies differently for each machine. You could somehow have a custom expected output format from which you can extract data like the gpu usage and the energy consumption.

**Comment by vkarak** [comment]
@omlins @teojgo This is a bit of a research topic, not so mature to enter the framework. Yes, there is correlation of performance and energy consumption but to my experience it's not as easy to state that the most energy is consumed by the memory, especially in an HPC environment. It really depends on the application/benchmark and on the underlying architecture. I see it more as application specific rather than as sth that should enter the framework.

**Comment by omlins** [comment]
Yes, absolutely, it is a research topic. I do not suggest to analyse the data now. I only suggest to make ReFrame allow to collect data, which can be analysed at some point later (independent of ReFrame).

**Comment by vkarak** [comment]
Yes, but I wouldn't change the framework for that. For the moment I have  not understood what is needed to collect this data and why and how should the framework be involved.

**Comment by omlins** [comment]
OK, there is certainly no hurry for that. I just wanted to note the idea.

**Comment by jgphpc** [comment]
We plan to report energy and gpu usage in xalt but we would need help in case you have extra time.

**Comment by jgphpc** [comment]
jobreport
