### ISSUE TITLE
Filtering tests by name does not work for multiple values

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#2483]
```
./bin/reframe --system=daint -C config/cscs.py -c cscs-checks/ -n  LAMMPSCPUCheck@1 -l  -n AlltoallvTest@0
```
The above will result in 0 tests found, while passing each name separately, works fine.

**Comment by ekouts** [comment]
Ah I had also seen this and I thought it was on purpose.. It's because we make one big regex in cli https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/cli.py#L924 but then, if the expression contains the `@` we check for exact match here https://github.com/eth-cscs/reframe/blob/master/reframe/frontend/filters.py#L31

**Comment by vkarak** [comment]
I think this is indeed a bug because chaining the `-n` option should be equivalent of ORing their requirements.
