### ISSUE TITLE
Move /apps/common/regression/resources to UES

### ISSUE THREAD

**Issue by jgphpc** [eth-cscs/reframe#355]
As discussed, we want to clean /apps/common to the minimum.
There are files in  /apps/common/regression/resources/
```
drwxr-s---  2 jenscscs csstaff  512 Aug 31  2017 HPCG
drwxr-s---  2 jenscscs csstaff  512 Feb 16 10:02 scalapack
drwxrws---  3 jenscscs csstaff  512 Jul 16 15:49 HPL
drwxrws---  3 jenscscs csstaff  512 Jul 16 15:49 Amber
drwxr-s---  2 jenscscs csstaff  512 Nov  2  2016 Espresso
drwxr-s---  2 jenscscs csstaff  512 Oct 25  2016 NAMD
drwxr-s---  5 jenscscs csstaff  512 Oct 27  2016 ior
drwxr-s---  8 jenscscs csstaff 4096 Dec 20  2017 HPCG-CPU
drwxr-s---  4 jenscscs csstaff 4096 Dec 22  2017 NCL
drwxr-s---  2 jenscscs csstaff 4096 Nov 16  2017 CDO-NCO
drwxr-s--- 21 jenscscs csstaff 4096 Sep  1  2017 OpenFOAM
drwxr-s--- 17 jenscscs csstaff 4096 Sep  7  2017 OpenFOAM-Extend
drwxr-sr-x  5 omlins   csstaff  512 Jun 19 14:39 cosmo_pompa_crclim
```
Can you move it to UES/ ?

**Comment by vkarak** [comment]
From the ReFrame's point of view, it's trivial; we need to just change the corresponding entry in the config file. However, we *need* to keep a symlink pointing to the new location, since such a change will break all the regression tests shipped with previous ReFrame versions. I suggest a transition period of at least two releases. @gppezzi What is your opinion?
