### ISSUE TITLE
Pass command line options to a regression test

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#563]
It would be nice to have the ability to pass command line options directly to a test. A use case is the following:

```
.
.
.

@rfm.cmd_parameterized_test:
class VariableGpuTest(rfm.RegressionTest):
    def __init__(self, num_gpus_per_node):
        super().__init__()
        self.num_gpus_per_node = num_gpus_per_node

.
.
.
```

Then we could run the test with `reframe -c variable_gpu_test.py --rfm-option='[1, 2, 3, 4]'`
which will make the test run with 4 different values of `num_gpus_per_node`.

**Comment by vkarak** [comment]
@teojgo Can you be more precise with this feature request. How would you like to program such a test? What you suggest in your description, it won't work.

- How the option should be named for each test?
- How a test specifies its arguments?

A more detailed user story is needed.

**Comment by vkarak** [comment]
Now with the variable syntax we can extend the API to simple select variable to expose at the command line, e.g., `num_nodes = variable(int, expose=True, conv=int)`

**Comment by jjotero** [comment]
I think that the strongest point from this feature is that it will enable us to register tests that have `required` variables, and then running the test without explicitly setting the variable in the test itself.
```python
@rfm.simple_test
class MyTest(rfm.RegressionTest):
    num_tasks = required
    ...
```
This is awesome because it just enables to run tests without coding any Python at all! 🚀

However, if the underlying test does explicitly set the value, I see three different scenarios for this depending on where this value is set. Here is how I think this should behave:

1. __The variable is set at the class level__: If a test just defines a given variable at the class level, the value provided through the cli will override the variable's original (default) value.

```python
@rfm.simple_test
class A(rfm.RunOnlyRegressionTest):
    ...
    num_tasks = 1
```
If a user runs this as
```bash
./bin/reframe ... -c <path_path_to_file> -r --set-defaults={num_tasks: 0}
```
(or whatever other cli option we go for to do this) the test `A` becomes a flexible test.

2. __The variable is set during the object construction__: If a test defines a given variable at the instance level before entering the pipeline (this is either in the `__init__` method or a post-init hook), the value provided through the cli will be overridden during construction.

```python
@rfm.simple_test
class B(rfm.RunOnlyRegressionTest):
    num_tasks = 1
    ...
    def __init__(self):
        print(self.num_tasks) # Prints 0 (the value passed from the cli)
        self.num_tasks = 10
```
If a user runs this with the same commands as above, the test `B` will set `self.num_tasks` to `10`, overriding the value passed from the cli. The reasoning behind this lies in the fact that the test could have a post-init hook where  the variable's value is updated. If the variable's value provided through the cli where to prevail over the one explicitly set in the hook, we would be silently overriding the hook. For example:
```python
@rfm.simple_test
class B_extended(B):
    @rfm.run_after('init')
    def update_num_tasks(self):
        print(self.num_tasks) # Prints 10 (the value set during the __init__)
        self.num_tasks = 100
```
Running `B_extended` should always have the `update_num_tasks` hook executed, otherwise, we would be silently overriding the hook (i.e. implicitly changing the test).

3. __The variable is set during any pipeline stage__: If a test defines a given variable after the test has entered the pipeline, the value provided through the cli will be overridden when the given pipeline hook executes.

```python
@rfm.simple_test
class C(rfm.RunOnlyRegressionTest):
    num_tasks = 1
    ...
    @rfm.run_before('run')
    def set_num_tasks(self):
        print(self.num_tasks) # Prints 0 (the value passed from the cli)
        self.num_tasks = 1
```
For the same reasoning as in __2__, the value provided from the cli will be overridden by the `set_num_tasks` hook. Not doing so would simply break the concept of the pipeline.

**Comment by jjotero** [comment]
What about if we pass a type hint alongside the variable's value from the command line?
