### ISSUE TITLE
Generate report in XML JUnit format

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#651]
This feature would allow ReFrame to generate an xml report in JUnit format used by Jenkins. The schema for the xml can be found [here](https://github.com/junit-team/junit5/blob/master/platform-tests/src/test/resources/jenkins-junit.xsd). A command line option which accepts the name of the output file should be added to make ReFrame generate the report after running the tests.

**Comment by vkarak** [comment]
Regarding the command line options, I think we can have two options: one for specifying the output type, e.g., (Junit, standard ReFrame report) and one for specifying the output file. The latter could be technically a different issue, because it could also replace the `reframe.out` file that we now specify in the logging settings.

**Comment by vkarak** [comment]
Now, that I'm thinking it again. This option cannot replace `reframe.out`. It is specifically for the report not the output.

**Comment by vkarak** [comment]
I've created issue #653 for creating the corresponding command line options.

**Comment by vkarak** [comment]
I'm raising the priority of this issue, because this feature would also be useful for reporting within Gitlab pipelines. I think we should pursue it.
