### ISSUE TITLE
Versions v2.13-v2.16 not found in documentation

### ISSUE THREAD

**Issue by teojgo** [eth-cscs/reframe#688]
When selecting another version from the latest documentation page, versions v2.13-v2.16 throw a `Page not found` error.

**Comment by kraushm** [comment]
This bug occurred, because the documentation of the corresponding versions had not been generated in the gh-pages branch with past version releases. 

However, this will be resolved with the Jira issue (https://jira.cscs.ch/browse/UES-144), i. e. moving the documentation of ReFrame to readthedocs.org.
