### ISSUE TITLE
ReFrame fails with Tcl versions that use modulecmd.tcl as executable

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/reframe#780]
ReFrame checks for the module system by running the `modulecmd` command.

Some versions of Tcl do not have the `modulecmd` binary. Instead they use the script `~/libexec/modulecmd.tcl` which is used by the `module` function in a similar way to `modulecmd`. They can not be replaced between each other, doing a symlink from `modulecmd.tcl` to `modulecmd` doesn't work as ReFrame gives `configuration error: could not find a sane Tmod installation`.

The details of the `module` function can be found with `type -a _moduleraw`. In the cases where the `modulecmd.tcl` is used, `module` depends on another function: `_moduleraw`. With `type -a _moduleraw` it can be seen that it used `libexec/modulecmd.tcl`.

**Comment by vkarak** [comment]
I don't think that we that it's safe to inspect the bash functions so as to retrieve the path of the `modulecmd`. We need `modulecmd` to be in path, cos this provides us the Python bindings. Of course, we can expand the backend to look for `modulecmd.tcl` if `modulecmd` is not found. We could also fine tune the error message, so that we instruct the user that we need `modulecmd` in the `PATH`. Documentation should also be updated.

**Comment by vkarak** [comment]
As discussed offline in #781, it seems that we don't support Tmod prior to 3.2 and Tmod 4.1.
