### ISSUE TITLE
`ssh`-style job launcher?

### ISSUE THREAD

**Issue by bcfriesen** [eth-cscs/reframe#880]
I have a few tests which need to run on particular nodes (not compute nodes) which are inaccessible by Slurm but are accessible by SSH. Would it be feasible to add something like an `ssh` launcher which SSH-es to a particular node and then runs a 'local' test?

An obvious workaround for this feature is to manually SSH to the relevant nodes and then run the tests there using the 'local' launcher. However that behavior requires significant manual intervention, whereas I would like to be able to automate this so that all tests can be run from a single place.

**Comment by vkarak** [comment]
Hi @bcfriesen, I guess you want sth like the following to be generated:

```
ssh [options] user@host command
```

I would see this as `local+ssh` scheduler/launcher combination. I think this is possible to do, but we will need to change how we manage the configuration options internally, in order to allow options to be passed to the scheduler/launcher always. Also, in a straightforward implementation, any variables modifying the environment of the test (e.g., `self.modules`, `self.variables`, current environment etc.) will not have an effect to the remote machine. Is this sth you want? Can you provide an example of what you would like to run?

**Comment by bcfriesen** [comment]
Hi @vkarak,

> Is this sth you want? Can you provide an example of what you would like to run?

There are a few use cases that are being considered:

- Running tests on certain eLogin nodes which are dedicated 'workflow' nodes (high memory, outside the SSH load balancer, etc.).
- Running tests on other types of service nodes which are not accessible from eLogins, and/or would require at least 1 SSH hop to access (e.g., SMW nodes, boot nodes, mom nodes).

I suspect that the types of tests we would like to run on those nodes would not require modules at all, so the inability to carry environment modifications to the remote machine I think would not be a big problem.
