### ISSUE TITLE
Score-P CUDA checks on Kesch

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#94]
Internal issue: https://madra.cscs.ch/scs/reframe/issues/119

**Comment by kraushm** [comment]
The ReFrame tests of Score-P cannot be ported to Kesch, due to issues with the installation of the software currently available on that machine. After discussion with @jgphpc and @vkarak, this issue will be addressed at a later point in time, when the new version of Score-P will be deployed on the CSCS systems. 

Therefore, the issue is removed from current sprints.

**Comment by vkarak** [comment]
Also, this is not required for the "Port to Kesch" project, so I am removing it from there, too.

**Comment by jgphpc** [comment]
No plan to support Score-P on Kesch
